version: '3'
services:
    streaming-app:
      build:
        context: .
        dockerfile: ./Dockerfile
      #restart: always ##production mode
      working_dir: /app
      ports:
        - "80:8080"
      depends_on:
        - db
        - redis
      environment:
        PORT: 8080
        MONGO_URL: mongodb://db:27017/streamingDB
        REDIS_URL: redis://redis
        NODE_ENV: production
      command: node server.js
    db:
      image: mongo
      #restart: always ##production mode
      ## setting the forwarding port of mongoDB
      ports: 
        - "27077:27017"
      volumes:
        - streaming-mongodata:/data/db
    redis:
      image: redis
      #restart: always ##production mode
      volumes:
        - ./docker-volumes-redis-data:/data
volumes:
  streaming-mongodata: