apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\lib\k8s\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  ports:
  - name: "27077"
    port: 27077
    targetPort: 27017
  selector:
    io.kompose.service: db
status:
  loadBalancer: {}
