apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: streaming-app
  name: streaming-app-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
