apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\lib\k8s\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: streaming-app
  name: streaming-app
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  selector:
    io.kompose.service: streaming-app
status:
  loadBalancer: {}
