apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: streaming-mongodata
  name: streaming-mongodata-claim
spec:
  storageClassName: mongodata #the pv storage name
  accessModes:
    - ReadWriteOnce #can read and write in one node
  resources:
    requests:
      storage: 3Gi
