apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\lib\k8s\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: streaming-app
  name: streaming-app
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    io.kompose.service: streaming-app
status:
  loadBalancer: {}
