apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\lib\k8s\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: web-server
  name: web-server
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: web-server
status:
  loadBalancer: {}
